### PR TITLE
Bugfix SmartParameter source code generation

### LINKED ISSUE #1177: Public types missing from reference assemblies don't work with ParamsSource
Consider the following benchmark:

```c#
using System;
using System.Collections.Generic;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Configs;
using BenchmarkDotNet.Environments;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Running;
using BenchmarkDotNet.Toolchains.CsProj;

class Program
{
    static void Main() => BenchmarkRunner.Run<Benchmark>();
}

public class MainConfig : ManualConfig
{
    public MainConfig()
    {
         Add(Job.Default.With(Platform.X64).With(CsProjCoreToolchain.NetCoreApp30));
         Options = ConfigOptions.KeepBenchmarkFiles;
    }
}

[Config(typeof(MainConfig))]
public class Benchmark
{
    public static IEnumerable<StringComparer> Comparers =>
        new[] { StringComparer.Ordinal };

    [ParamsSource(nameof(Comparers))]
    public StringComparer Comparer;

    [Benchmark]
    public void B() { }
}
```

When I attempt to run it, I get the following error:

> Job-YBSJDZ.notcs(125,41): error CS0234: The type or namespace name 'OrdinalComparer' does not exist in the namespace 'System' (are you missing an assembly reference?) [C:\code\tmp\hwapp\bin\Release\netcoreapp3.0\Job-YBSJDZ\BenchmarkDotNet.Autogenerated.csproj]

The relevant generated code is:

```c#
instance.Comparer = (System.OrdinalComparer)System.Linq.Enumerable.ToArray(Benchmark.Comparers)[0];;
```

The problem here is that for some reason (https://github.com/dotnet/corert/commit/83bcbe0), the actual type of `StringComparer.Ordinal`, `OrdinalComparer` is `public`, but it does not exist in reference assemblies. This means that the C# compiler won't see it, but the BDN code generator will consider it as the correct type to generate: 

https://github.com/dotnet/BenchmarkDotNet/blob/0a4550f6ab0b821f31f59806b682dace8296ba54/src/BenchmarkDotNet/Extensions/ReflectionExtensions.cs#L40

### LINKED ISSUE #1812: Invalid codegen for Enumerable.Empty returned from ParamsSource
**Description:**
Attempt to parameterize property of type `IEnumerable<T>` with `Enumerable.Empty<T>()` or `Enumerable.Repeat<T>(element, count)` using `ParamsSource` attribute causes compilation error in codegen compilation error _CS0266: Cannot implicitly convert type 'object' to 'System.Collections.Generic.IEnumerable<int>'. An explicit conversion exists (are you missing a cast?)_ because of lines like
```cs
instance.A = (System.Object)BenchmarkDotNet.Parameters.ParameterExtractor.GetParameter(instance.ValuesForA, 1);;
```

**Benchmark code:** 
```cs
public class ParamsSourceIntro
{
    public IEnumerable<IEnumerable<int>> ValuesForA()
    {
        yield return Enumerable.Empty<int>();
        yield return Enumerable.Repeat(1, 1);
    }

    [ParamsSource(nameof(ValuesForA))]
    public IEnumerable<int> A { get; set; }

    [Benchmark]
    public int[] Benchmark() => A.ToArray();
}

class Program
{
    static void Main(string[] args)
    {
        var _ = BenchmarkRunner.Run<ParamsSourceBug>();
    }
}
```

**Logs:**
Log with compilation error: [BenchmarkDotNetParamsSourceBug.ParamsSourceBug-20210923-021529.log](https://github.com/dotnet/BenchmarkDotNet/files/7214383/BenchmarkDotNetParamsSourceBug.ParamsSourceBug-20210923-021529.log)
 Autogenerated project: [397b1fac-e83d-4694-8454-8c0fcba111a5.zip](https://github.com/dotnet/BenchmarkDotNet/files/7214348/397b1fac-e83d-4694-8454-8c0fcba111a5.zip)

**Workarounds:**
1. Use ArgumentsSource attribute;
2. Change type of parameterized property to object and cast it back later;
3. Wrap IEnumerable<T> in it's own type `record Wrapper<T>(IEnumerable<T> Collection)`.

### LINKED ISSUE #2011: Release-only build error when using ParamsSource with a LINQ method: Cannot implicitly convert type 'object'
I believe this might be a bug in BDN 0.13.1, though I have tried 0.12.0 and 0.12.1 and had issues with those versions as well - granted, slightly different issues.

This is on Net6.0, in a solution with both C# and F# code.

`0.13.1`:

> // Found 27 benchmarks:
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array1, FSharpBenchmark=Blog1]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array1, FSharpBenchmark=Blog2]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array1, FSharpBenchmark=Blog3]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array1, FSharpBenchmark=Blog4]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array1, FSharpBenchmark=Blog5]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array1, FSharpBenchmark=Blog6]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array1, FSharpBenchmark=Blog7]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array1, FSharpBenchmark=Quicksort1]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array1, FSharpBenchmark=Quicksort2]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array2, FSharpBenchmark=Blog1]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array2, FSharpBenchmark=Blog2]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array2, FSharpBenchmark=Blog3]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array2, FSharpBenchmark=Blog4]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array2, FSharpBenchmark=Blog5]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array2, FSharpBenchmark=Blog6]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array2, FSharpBenchmark=Blog7]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array2, FSharpBenchmark=Quicksort1]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array2, FSharpBenchmark=Quicksort2]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array3, FSharpBenchmark=Blog1]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array3, FSharpBenchmark=Blog2]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array3, FSharpBenchmark=Blog3]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array3, FSharpBenchmark=Blog4]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array3, FSharpBenchmark=Blog5]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array3, FSharpBenchmark=Blog6]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array3, FSharpBenchmark=Blog7]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array3, FSharpBenchmark=Quicksort1]
//   InjectedFSharpQuicksortBenchmarks.FSharpQuicksorts: DefaultJob [FSharpData=FSharp - Array3, FSharpBenchmark=Quicksort2]
// Build Error: Standard output:
 Standard error:
 Time Elapsed 00:00:01.49
    27 Error(s)
    0 Warning(s)
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(12600,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(14796,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(14064,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(13332,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(11868,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(15528,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(11136,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(10404,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(16260,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(9672,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(8940,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(8208,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(7476,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(5280,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(6012,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(6744,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(16992,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(4548,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(17724,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(3816,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(3084,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(18456,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(2352,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(156,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(19188,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(1620,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(888,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
Build FAILED.
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(12600,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(14796,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(14064,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(13332,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(11868,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(15528,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(11136,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(10404,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(16260,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(9672,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(8940,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(8208,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(7476,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(5280,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(6012,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(6744,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(16992,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(4548,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(17724,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(3816,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(3084,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(18456,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(2352,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(156,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(19188,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(1620,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\08f4e2d5-bf72-436a-a197-73cf761f1905.notcs(888,35): error CS0266: Cannot implicitly convert type 'object' to 'Benchmarks.Abstract.IFSharpQuicksortDataSource'. An explicit conversion exists (are you missing a cast?) [D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905\BenchmarkDotNet.Autogenerated.csproj]
Copyright (C) Microsoft Corporation. All rights reserved.
Microsoft (R) Build Engine version 17.1.1+a02f73656 for .NET
// BenchmarkDotNet has failed to build the auto-generated boilerplate code.
// It can be found in D:\git\fsharp.project1\Benchmarks\bin\Release\net6.0\08f4e2d5-bf72-436a-a197-73cf761f1905
// Please follow the troubleshooting guide: https://benchmarkdotnet.org/articles/guides/troubleshooting.html
// ** Remained 0 benchmark(s) to run **
Run time: 00:00:00 (0.1 sec), executed benchmarks: 0

I've been able to narrow down the issue to this approach to generating parameterized benchmark data:
```csharp
public class InjectedFSharpQuicksortBenchmarks
{
    private readonly Consumer consumer = new Consumer();

    public static IEnumerable<IFSharpQuicksortDataSource> FSharpDataSources()
    {
        // throws build error in RELEASE, but works in DEBUG compilation
        var converter = new CSharpToFSharpQuicksortDataSourceConverter();

        return InjectedCSharpQuicksortBenchmarks.CSharpDataSources().Select(x => converter.Convert(x));
    }

    [ParamsSource(nameof(FSharpDataSources))]
    public IFSharpQuicksortDataSource FSharpData { get; set; }

    public static IEnumerable<IFSharpQuicksortBenchmark> FSharpBenchmarks()
    {
        // omitted for brevity
    }

    [ParamsSource(nameof(FSharpBenchmarks))]
    public IFSharpQuicksortBenchmark FSharpBenchmark { get; set; }

    [Benchmark]
    public void FSharpQuicksorts()
    {
        FSharpBenchmark.Run(FSharpData.Data).Consume(consumer);
    }
}
```

However, if I change this approach to use classes directly, I do not encounter the issue:
```csharp
public class InjectedFSharpQuicksortBenchmarks
{
    private readonly Consumer consumer = new Consumer();

    public static IEnumerable<IFSharpQuicksortDataSource> FSharpDataSources()
    {
        // works fine
        yield return new FSharpQuickSortArray1DataSource();
        yield return new FSharpQuickSortArray2DataSource();
        yield return new FSharpQuickSortArray3DataSource();
    }

    [ParamsSource(nameof(FSharpDataSources))]
    public IFSharpQuicksortDataSource FSharpData { get; set; }

    public static IEnumerable<IFSharpQuicksortBenchmark> FSharpBenchmarks()
    {
        // omitted for brevity
    }

    [ParamsSource(nameof(FSharpBenchmarks))]
    public IFSharpQuicksortBenchmark FSharpBenchmark { get; set; }

    [Benchmark]
    public void FSharpQuicksorts()
    {
        FSharpBenchmark.Run(FSharpData.Data).Consume(consumer);
    }
}
```

Related classes:
```csharp
// multiple similar classes to this, with different int[] arrays 
public class CSharpQuicksortArray1DataSource : ICSharpQuicksortDataSource
{
    public string Category => "Array1";

    public int[] Data { get; } = BenchmarksData.A1;

    public override string ToString() => Category;
}

// packages up a CSharp int[] into an FSharpList<int> for the F# implementation
public class CSharpToFSharpQuicksortDataSourceConverter : ICSharpToFSharpQuicksortDataSourceConverter
{
    public IFSharpQuicksortDataSource Convert(ICSharpQuicksortDataSource data)
    {
        return new FSharpQuickSortDataSource(data.Data, data.Category);
    }

    private class FSharpQuickSortDataSource : IFSharpQuicksortDataSource
    {
        public FSharpList<int> Data { get; }
        public string Category { get; }
        
        public FSharpQuickSortDataSource(IEnumerable<int> data, string category)
        {
            Data = ListModule.OfSeq(data);
            Category = category;
        }
        
        public override string ToString()
        {
            return $"FSharp - {Category}";
        }
    }
}

// multiple similar classes to this, with different int[] arrays packaged into FSharpList<int>
public class FSharpQuickSortArray1DataSource : IFSharpQuicksortDataSource
{
    public string Category => "Array1";

    public FSharpList<int> Data { get; } = ListModule.OfSeq(BenchmarksData.A1);

    /// <summary>Returns a string that represents the current object.</summary>
    /// <returns>A string that represents the current object.</returns>
    public override string ToString() => Category;
}
```

I'm curious if I'm doing something that is strictly unsupported here, or if this is just an odd edge case I've found myself in.

Solution to reproduce this can be found [here](https://github.com/cthompson92/benchmarkdotnet-bug-2011-repro)

### PR DESCRIPTION
**Pull request by mawosoft**
SmartParameter codegen must use the target type for casting, not the type of the source value.
Basically, this is a follow up to PR #1228 (1678a49a7b044b7915c3cbcd64300501cfef9035), which fixed this problem for SmartArgument.
EDIT: ~Fixes #2011. Probably also #1812 and a few similar issues reported in the past.~
Fixes #2011, fixes #1812, fixes #1177.

@adamsitnik 
Not sure yet if the fix is complete or if the shortcuts in `SmartParamBuilder.CreateForParams()` that bypass the creation of `SmartParameter` instances have to be removed. Same for `BenchmarkConverter.GetValidValues()`.
(test failures are unrelated, though)

### CODE REVIEW

**Review by adamsitnik — COMMENTED** [review]
@mawosoft overall it looks good to me, but could you please add a test that verifies the fix?

https://github.com/dotnet/BenchmarkDotNet/blob/master/tests/BenchmarkDotNet.IntegrationTests/ArgumentsTests.cs

**Comment by mawosoft** [comment]
@adamsitnik 
Should the tests go into ArgumentsTests or did you mean that as a template for more thoroughly tests? There are also these

https://github.com/dotnet/BenchmarkDotNet/blob/master/tests/BenchmarkDotNet.IntegrationTests/ParamSourceTests.cs

https://github.com/dotnet/BenchmarkDotNet/blob/master/tests/BenchmarkDotNet.IntegrationTests/ParamsAttributeStaticTest.cs

https://github.com/dotnet/BenchmarkDotNet/blob/master/tests/BenchmarkDotNet.IntegrationTests/ParamsTests.cs

As I said, I have to take a second look to see if the fix is complete, but with added tests, I should get an answer to this.

**Comment by adamsitnik** [comment]
Just adding a failing test to one of the mentioned files should be enough

File: tests/BenchmarkDotNet.IntegrationTests/ParamSourceTests.cs [hunk 1]
```diff
@@ -35,5 +50,159 @@ public IEnumerable<string> StringValues
...
+        private Summary CanExecuteWithExtraInfo(Type type, IToolchain toolchain)
+        {
+            IConfig config = CreateSimpleConfig(job: Job.Dry.WithToolchain(toolchain));
+            // Show the relevant codegen excerpt in test results (the *.notcs is not part of the logs)
+            // This uses the private static CodeGenerator.GetParamsContent() method.
+            // Method changes there must be applied here - or consider making the method internal.
+            // TODO Should we omit the extra info if (toolchain.IsInProcess)? Doesn't use GetParamsContent().
+            Output.WriteLine("// Benchmarks and CodeGenerator.GetParamsContent()");
+            BenchmarkRunInfo runInfo = BenchmarkConverter.TypeToBenchmarks(type, config);
+            MethodInfo getParamsContent = typeof(Code.CodeGenerator).GetMethod("GetParamsContent", BindingFlags.Static | BindingFlags.NonPublic, null, new[] { typeof(BenchmarkCase) }, null);
```
Comment (mawosoft) [inline tests/BenchmarkDotNet.IntegrationTests/ParamSourceTests.cs:63]: I added a bit of a hack to add extra info to the test results. If that's frowned upon, I can remove it.

Comment (mawosoft) [inline tests/BenchmarkDotNet.IntegrationTests/ParamSourceTests.cs:63]: I added a bit of a hack to add extra info to the test results. If that's frowned upon, I can remove it.

File: tests/BenchmarkDotNet.IntegrationTests/ParamSourceTests.cs [hunk 2]
```diff
@@ -35,5 +50,159 @@ public IEnumerable<string> StringValues
...
+        public void PrivateClassWithPublicInterface_AsObject_Succeeds(IToolchain toolchain) => CanExecuteWithExtraInfo(typeof(PrivateClassWithPublicInterface_AsObject), toolchain);
+
+        public class PublicSource
+        {
+            public int Data { get; }
+            public PublicSource(int data) => Data = data;
+            // Notes:
+            // - op_Implicit would be meaningless since codegen wouldn't have to do anything.
+            // - TODO op_Explicit is currently not supported by InProcessEmitToolchain (See TryChangeType() in Toolchains/InProcess.Emit.Implementation/Runnable/RunnableReflectionHelpers.cs)
+            public static explicit operator TargetType(PublicSource @this) => @this != null ? new TargetType(@this.Data) : null;
```
Comment (mawosoft) [inline tests/BenchmarkDotNet.IntegrationTests/ParamSourceTests.cs:171]: Not sure if op_Explicit support should be added to TryChangeType().

**Review by mawosoft — COMMENTED** [review]
@adamsitnik I added some tests, should be ready for review now.
I didn't rebase this branch, so the NativeAOT test failures will still pop up.

**Review by adamsitnik — APPROVED** [review]
:shipit: ! thank you one more time @mawosoft !
