### PR TITLE
Fix #1731.

### LINKED ISSUE #1731: Error when run benchmark
### System info
- OS: MacOS BigSur 11.4
- Runtime: .NET Core 3.1.16 (CoreCLR 4.700.21.26205, CoreFX 4.700.21.26205), X64 RyuJIT

### Error
```
// AfterAll
// The benchmarking process did not quit on time, it's going to get force killed now.
Unhandled exception. System.InvalidOperationException: Process must exit before requested information can be determined.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, ArtifactsPaths artifactsPaths, IDiagnoser diagnoser, String executableName, IResolver resolver)
   at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(ExecuteParameters executeParameters)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunExecute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver, IDiagnoser diagnoser, Boolean& success)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String resultsFolderPath, String logFilePath, StartedClock& runChronometer)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config, Boolean askUserForInput)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at benchmarks.Program.Main(String[] args) in <redacted>../benchmarks/Program.cs:line 7
```

It seems like that the code under benchmark is slow (or it doesn't free resources on time) which causes waiting more than 250 ms: https://github.com/dotnet/BenchmarkDotNet/blob/75f63272def862bb223a3e3e040760a71d8994d1/src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliExecutor.cs#L91

### PR DESCRIPTION
**Pull request by cgranade**
This PR fixes #1731 by:

- Increasing process exit timeout from 250 to 2000 milliseconds.
- Waiting 500 milliseconds for `KillProcessTree()` to work.
- Guarding `process.ExitCode` on `process.HasExited` and giving more meaningful error messages for hung benchmarking processes.

Thank you!

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/BenchmarkDotNet?pullRequest=1745) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/BenchmarkDotNet?pullRequest=1745) before we can accept your contribution.<br/><br/>:x: cgranade [sign now](https://cla.dotnetfoundation.org/dotnet/BenchmarkDotNet?pullRequest=1745)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/BenchmarkDotNet?pullRequest=1745) it.</sub>

File: src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliExecutor.cs [hunk 1]
```diff
@@ -21,6 +22,7 @@ public class DotNetCliExecutor : IExecutor
         public DotNetCliExecutor(string customDotNetCliPath) => CustomDotNetCliPath = customDotNetCliPath;
 
         private string CustomDotNetCliPath { get; }
+        private readonly TimeSpan ProcessExitTimeout = TimeSpan.FromSeconds(2);
```
Comment (adamsitnik) [inline src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliExecutor.cs:25]: since it's more or less a const, we can make it `static`

```suggestion
        private static readonly TimeSpan ProcessExitTimeout = TimeSpan.FromSeconds(2);
```

File: src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliExecutor.cs [hunk 2]
```diff
@@ -88,14 +90,16 @@ public ExecuteResult Execute(ExecuteParameters executeParameters)
...
 
-                if (!process.WaitForExit(milliseconds: 250))
+                if (!process.WaitForExit(milliseconds: (int)ProcessExitTimeout.TotalMilliseconds))
                 {
-                    logger.WriteLineInfo("// The benchmarking process did not quit on time, it's going to get force killed now.");
+                    logger.WriteLineInfo($"// The benchmarking process did not quit within {ProcessExitTimeout.TotalSeconds} seconds, it's going to get force killed now.");
 
                     consoleExitHandler.KillProcessTree();
+                    // Give KillProcessTree a few moments to actually kill the benchmarking process.
+                    Thread.Sleep(millisecondsTimeout: 500);
```
Comment (adamsitnik) [inline src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliExecutor.cs:99]: `KillProcessTree` calls `KillTree`
https://github.com/dotnet/BenchmarkDotNet/blob/63e28c100a42a6492d09a0b93a8a4c141061bb0d/src/BenchmarkDotNet/Helpers/ConsoleExitHandler.cs#L60-L66

which uses the default timeout of 30s:
https://github.com/dotnet/BenchmarkDotNet/blob/63e28c100a42a6492d09a0b93a8a4c141061bb0d/src/BenchmarkDotNet/Extensions/ProcessExtensions.cs#L138

https://github.com/dotnet/BenchmarkDotNet/blob/63e28c100a42a6492d09a0b93a8a4c141061bb0d/src/BenchmarkDotNet/Extensions/ProcessExtensions.cs#L23

so the extra sleep should not be needed

```suggestion
```

**Review by adamsitnik — COMMENTED** [review]
@cgranade big thanks for your PR! I left two comments, otherwise than that LGTM, but please address them before we merge the PR

**Comment by cgranade** [comment]
@adamsitnik Thanks for the review and for the suggestions, I've committed both to my PR. Thanks for an awesome project! ♥

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you @cgranade!
