### PR TITLE
[chore]: fix error message

### LINKED ISSUE #2378: BenchmarkDotNet requires dotnet cli to be installed
When running a Benchmark on Ubuntu (with .NET runtime installed) I get this error:

"BenchmarkDotNet requires dotnet cli to be installed"

I suggest changing that message to 

"BenchmarkDotNet requires dotnet **_SDK_** to be installed"

Because it's confusing.

### PR DESCRIPTION
**Pull request by BurakTaner**
Fixes #2378

Changed validation error message from:

```text 
"BenchmarkDotNet requires dotnet cli to be installed"
```

to

```text
"BenchmarkDotNet requires dotnet sdk to be installed"
```

### CODE REVIEW

File: src/BenchmarkDotNet/Toolchains/Toolchain.cs [hunk 1]
```diff
@@ -64,7 +64,7 @@ internal static bool IsCliPathInvalid(string customDotNetCliPath, BenchmarkCase
             if (string.IsNullOrEmpty(customDotNetCliPath) && !HostEnvironmentInfo.GetCurrent().IsDotNetCliInstalled())
             {
                 validationError = new ValidationError(true,
-                    $"BenchmarkDotNet requires dotnet cli to be installed or path to local dotnet cli provided in explicit way using `--cli` argument, benchmark '{benchmarkCase.DisplayInfo}' will not be executed",
+                    $"BenchmarkDotNet requires dotnet sdk to be installed or path to local dotnet cli provided in explicit way using `--cli` argument, benchmark '{benchmarkCase.DisplayInfo}' will not be executed",
```
Comment (adamsitnik) [inline src/BenchmarkDotNet/Toolchains/Toolchain.cs:67]: nit: I would uppercase the SDK

```suggestion
                    $"BenchmarkDotNet requires dotnet SDK to be installed or path to local dotnet cli provided in explicit way using `--cli` argument, benchmark '{benchmarkCase.DisplayInfo}' will not be executed",
```

**Review by adamsitnik — COMMENTED** [review]
@BurakTaner thank you for your contribution!
