### PR TITLE
Use ArtifactsPath

### LINKED ISSUE #2425: `WithCustomBuildConfiguration` breaks build
### Discussed in https://github.com/dotnet/BenchmarkDotNet/discussions/2424

<div type='discussions-op-text'>

<sup>Originally posted by **SebastianStehle** September  2, 2023</sup>
Hi,

I want to benchmark with local version of the library with previous nuget versions. Therefore I have created the following setup:

Code for that can be found at: 
https://github.com/SebastianStehle/mjml-net/blob/main/Mjml.Net.Benchmark/TemplateBenchmarks.cs

1. Define multiple jobs:

```
var baseJob = Job.ShortRun;

            AddJob(baseJob
                .WithId("Dev").WithBaseline(true));

            AddJob(baseJob.WithCustomBuildConfiguration("V1_24")
                .WithId("1.24.0"));

            AddJob(baseJob.WithCustomBuildConfiguration("V2_0")
                .WithId("2.0.0"));

            AddJob(baseJob.WithCustomBuildConfiguration("V2_1")
                .WithId("2.1.0"));
```

2. Load the nuget version based on configuration:

```
<ItemGroup Condition="'$(Configuration)'=='V1_24'">
	<PackageReference Include="Mjml.Net" Version="1.24.0" />
  </ItemGroup>
	
  <ItemGroup Condition="'$(Configuration)'=='V2_0'">
	<PackageReference Include="Mjml.Net" Version="2.0.0" />
  </ItemGroup>
	
  <ItemGroup Condition="'$(Configuration)'=='V2_1'">
	<PackageReference Include="Mjml.Net" Version="2.1.0-beta1" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)'=='Debug'">
    <ProjectReference Include="..\Mjml.Net\Mjml.Net.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)'=='Release'">
    <ProjectReference Include="..\Mjml.Net\Mjml.Net.csproj" />
  </ItemGroup>
```

But when I run it I get errors like this:

```
// Execute: dotnet 8013b23c-cfa0-4303-a97b-ce66f7c64415.dll --anonymousPipes 1412 4632 --benchmarkName "Mjml.Net.Benchmarking.TemplateBenchmarks.Render_Template_Minify(MjmlTemplateFilePath: \"./Templates/Amario.mjml\")" --job 1.24.0 --benchmarkId 1 in D:\mjml\mjml-net\Mjml.Net.Benchmark\bin\Release\net7.0\8013b23c-cfa0-4303-a97b-ce66f7c64415\bin\V1_24\net7.0
// BeforeAnythingElse

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Mjml.Net, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Mjml.Net, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Mjml.Net.Benchmarking.TemplateBenchmarks..ctor()
   at BenchmarkDotNet.Autogenerated.Runnable_1..ctor() in D:\mjml\mjml-net\Mjml.Net.Benchmark\bin\Release\net7.0\8013b23c-cfa0-4303-a97b-ce66f7c64415\8013b23c-cfa0-4303-a97b-ce66f7c64415.notcs:line 395
   at BenchmarkDotNet.Autogenerated.Runnable_1.Run(IHost host, String benchmarkName) in D:\mjml\mjml-net\Mjml.Net.Benchmark\bin\Release\net7.0\8013b23c-cfa0-4303-a97b-ce66f7c64415\8013b23c-cfa0-4303-a97b-ce66f7c64415.notcs:line 339
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in D:\mjml\mjml-net\Mjml.Net.Benchmark\bin\Release\net7.0\8013b23c-cfa0-4303-a97b-ce66f7c64415\8013b23c-cfa0-4303-a97b-ce66f7c64415.notcs:line 57
// AfterAll
```

For me it seems that it tries to build with the wrong version. If I check the bin folder, I actually see the 2.0.0 version of the dll. there, but if I build with  `dotnet build -c V1_24` the correct version is used.

It seems that i am doing something wrong.</div>

### LINKED ISSUE #2664: Starting CLI Commands no longer works via the dotnet-runtime-host ".exe"
Since 0,14 and the new build system it seems like you can no longer start other referenced cli projects via Process.Start in BenchmarkDotNet.

Background: It seems like the embedded dll is always the one from BenchmarkDotNet now.

This is a COREHOST_TRACE=1 capture of the started project
```
Tracing enabled @ Wed Nov 13 14:41:27 2024 GMT
--- Invoked apphost [version: 8.0.11 @Commit: 9cb3b725e3ad2b57ddc9fb2dd48d2d170563a8f5] main = {
C:\Dev\TestProj\Src\TestPerfRunner\bin\Net6\Release\net8.0-windows\f4d0ff40-a7b1-4376-b14d-87ef1f70a014\bin\Release\net8.0-Windows7.0\OtherProject.exe
config=C:\Dev\TestProj\Src\TestPerfRunner\bin\Net6\Release\net8.0-windows\f4d0ff40-a7b1-4376-b14d-87ef1f70a014\bin\Release\net8.0-Windows7.0\epsSingle.config
}
Redirecting errors to custom writer.
The managed DLL bound to this executable is: 'f4d0ff40-a7b1-4376-b14d-87ef1f70a014.dll'
```

The problem is it should be 'OtherProject.dll' instead since that is a completely other project.

The problem only materializes when you use a command line which can not be parsed by the BDN dll and your output will be:

```
// BeforeAnythingElse

System.FormatException: The input string 'config=C:\Dev\TestProj\Src\TestPerfRunner\bin\Net6\Release\net8.0-windows\f4d0ff40-a7b1-4376-b14d-87ef1f70a014\bin\Release\net8.0-Windows7.0\epsSingle.config' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Int32.Parse(String s)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in C:\Dev\TestProj\Src\TestPerfRunner\bin\Net6\Release\net8.0-windows\f4d0ff40-a7b1-4376-b14d-87ef1f70a014\f4d0ff40-a7b1-4376-b14d-87ef1f70a014.notcs:line 45
// AfterAll
```
Instead of running the correct entry point.

Workaround:

we now start `dotnet <OtherProject.dll>` instead but it was quite the pain to find and debug this problem, since if you open the .exe or the .dll in DotPeek everything looks nice, and if you don't have actual parameters it will forward to the 'correct' entrypoint.

### PR DESCRIPTION
**Pull request by timcassell**
Fixes #2425
Fixes #2664

We set `ArtifactsPath` if the dotnet sdk used supports it (v8.0 or higher). Older sdks still use the same build logic as previous, and as far as I could find out, it's the best we can do for those older sdks.
Passing `ArtifactsPath` also makes MSBuild output publish directory differently by default, so we pass `PublishDir` also to work for both old and new sdks.

### CODE REVIEW

**Comment by timcassell** [comment]
@adamsitnik Based on your comment https://github.com/dotnet/BenchmarkDotNet/issues/2693#issuecomment-2615638065, should we just always use ArtifactsPath and not worry about older sdks here?

**Comment by filzrev** [comment]
I want to use this PR feature for benchmarks that use multi NuGet versions.

Is it possible to raise priority for review/merge?
And available as nightly build package?

**Review by AndreyAkinshin — CHANGES_REQUESTED** [review]
The end of support for .NET SDK 7.0 is May 14, 2024, which is about a year away. I suggest dropping support for .NET SDK 7 and requiring .NET SDK 8 or higher. This change would allow us to use ArtifactsPath everywhere by default, eliminating the need to pass `useArtifactsPath` repeatedly. Additionally, we should implement a warning for users attempting to run BenchmarkDotNet with older versions of the SDK.

**Comment by timcassell** [comment]
Updated to your feedback. If we merge #2721, we can update the warning message to tell the user to disable parallel builds (or we could do it automatically).

File: src/BenchmarkDotNet/Validators/DotNetSdkValidator.cs [hunk 1]
```diff
@@ -20,30 +20,45 @@ public static IEnumerable<ValidationError> ValidateCoreSdks(string? customDotNet
...
                 yield break;
             }
 
             var installedVersionString = cachedFrameworkSdks.Value.FirstOrDefault();
-
             if (installedVersionString == null || Version.TryParse(installedVersionString, out var installedVersion) && installedVersion < requiredSdkVersion)
             {
                 yield return new ValidationError(true, $"The required .NET Framework SDK version {requiredSdkVersion} or higher is not installed.", benchmark);
             }
+            else if (requiredSdkVersion.Major < 8)
```
Comment (timcassell) [inline src/BenchmarkDotNet/Validators/DotNetSdkValidator.cs:58]: Upon review, I think this check will always fail. I'm not sure how to determine whether the dotnet core sdk will successfully use ArtifactsPath when building older tfms. @rainersigwald Does sdk 8+ always use ArtifactsPath, or does it delegate the build to the older sdks?

**Review by AndreyAkinshin — APPROVED** [review]
