### PR TITLE
Fix Merge operation failed for EtwProfiler

### LINKED ISSUE #1544: [EtwProfiler] Merge operation failed return code 0x3
Reported by @DrewScoggins via an email message:

> If you run this command py .\scripts\benchmarks_ci.py -f netcoreapp5.0 --bdn-arguments="--anyCategories Libraries Runtime -p ETW" --filter *RentReturnArrayPoolTests<Byte>.SingleSerial*, you get an exception when trying to merge. I have not dug into this, but I have been able to reliably repro it.

```log
[2020/09/25 17:29:39][INFO] Unhandled exception. System.Exception: Merge operation failed return code 0x3
[2020/09/25 17:29:39][INFO]    at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.Merge(String[] inputETLFileNames, String outputETLFileName, EVENT_TRACE_MERGE_EXTENDED_DATA flags)
[2020/09/25 17:29:39][INFO]    at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.Merge(String[] inputETLFileNames, String outputETLFileName, TraceEventMergeOptions options)
[2020/09/25 17:29:39][INFO]    at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.MergeInPlace(String etlFileName, TextWriter log)
[2020/09/25 17:29:39][INFO]    at BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.Stop(DiagnoserActionParameters parameters)
[2020/09/25 17:29:39][INFO]    at BenchmarkDotNet.Diagnostics.Windows.EtwProfiler.Handle(HostSignal signal, DiagnoserActionParameters parameters)
[2020/09/25 17:29:39][INFO]    at BenchmarkDotNet.Diagnosers.CompositeDiagnoser.Handle(HostSignal signal, DiagnoserActionParameters parameters)
[2020/09/25 17:29:39][INFO]    at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(ExecuteParameters executeParameters)
[2020/09/25 17:29:39][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver)
[2020/09/25 17:29:39][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult)
[2020/09/25 17:29:39][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String resultsFolderPath, String logFilePath, StartedClock& runChronometer)
[2020/09/25 17:29:39][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
[2020/09/25 17:29:39][INFO]    at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config)
[2020/09/25 17:29:39][INFO]    at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
[2020/09/25 17:29:39][INFO]    at MicroBenchmarks.Program.Main(String[] args) in C:\git\performance\src\benchmarks\micro\Program.cs:line 41
```

### PR DESCRIPTION
**Pull request by adamsitnik**
Fixes #1544 

to tell the long story short, if Long Paths support is enabled on Windows, the ETW might still throw errors.

The fix is to always use 260 characters limit

### CODE REVIEW

**Comment by adamsitnik** [comment]
@AndreyAkinshin PTAL

File: src/BenchmarkDotNet/Helpers/ArtifactFileNameHelper.cs [hunk 1]
```diff
@@ -18,7 +19,11 @@ internal static string GetTraceFilePath(DiagnoserActionParameters details, DateT
         {
             string nameNoLimit = GetFilePathNoLimits(details, creationTime, fileExtension);
 
-            int limit = PathFeatures.AreAllLongPathsAvailable() ? CommonSenseLimit : WindowsOldPathLimit;
+            // long paths can be enabled on Windows but it does not mean that ETW is going to work fine..
+            // so we always use 260 as limit on Windows
+            int limit =  RuntimeInformation.IsWindows()
+                ? WindowsOldPathLimit - "userheap.etl".Length // the session files get merged, they need to have same name (without extension)
```
Comment (WojciechNagorski) [inline src/BenchmarkDotNet/Helpers/ArtifactFileNameHelper.cs:25]: You could reuse HeapSession.FileExtension. I checked it seems to be the longest extension, so it is a good solution.

File: tests/BenchmarkDotNet.Tests/ArtifactFileNameHelperTests.cs [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+            }
+        }
+    }
+}
+
+namespace System.Buffers.Tests
+{
+    [GenericTypeArguments(typeof(byte))] // value type
+    [GenericTypeArguments(typeof(object))] // reference type
+    public class RentReturnArrayPoolTests<T>
```
Comment (WojciechNagorski) [inline tests/BenchmarkDotNet.Tests/ArtifactFileNameHelperTests.cs:43]: Why do you need such a complicated example?

**Review by WojciechNagorski — COMMENTED** [review]
@adamsitnik IMO you fixed the problem but I have some minor comments.

File: tests/BenchmarkDotNet.Tests/ArtifactFileNameHelperTests.cs (hunk 2 above)
Comment (adamsitnik) [reply tests/BenchmarkDotNet.Tests/ArtifactFileNameHelperTests.cs:43]: @WojciechNagorski to get a benchmark with a very long name. I was lazy and I just copied it 1:1 from the bug report

File: src/BenchmarkDotNet/Helpers/ArtifactFileNameHelper.cs (hunk 1 above)
Comment (adamsitnik) [reply src/BenchmarkDotNet/Helpers/ArtifactFileNameHelper.cs:25]: > You could reuse HeapSession.FileExtension

I was thinking about it. The problem is that it's an instance property - so I would need to have an `HeapSession` instance to get it.

Then I was thinking about introducing an `internal const string` field to the `HeapSession` but it was far from perfect: 
* I would need two names for the same thing
* it would be still possible to introduce a new session type with a longer name.

I think that we can keep it as it is until we find a better solution.

**Review by AndreyAkinshin — APPROVED** [review]
